export const DEFAULT_CARS = [
  {
    _id: '1',
    name: '911 Carrera',
    brand: 'Porsche',
    model: 'Carrera',
    image: '/cars/porsche-911.jpg',
    price: 34375000,
    category: 'sports',
    year: 2024,
    description: 'Iconic sports car with legendary performance and precision engineering',
    specifications: {
      engine: '3.0L Twin-Turbo Flat-6',
      horsepower: 443,
      topSpeed: 183,
    },
  },
  {
    _id: '2',
    name: 'Continental GT',
    brand: 'Bentley',
    model: 'Continental',
    image: '/cars/bentley-continental.jpg',
    price: 63250000,
    category: 'luxury',
    year: 2024,
    description: 'Ultimate expression of luxury and British craftsmanship',
    specifications: {
      engine: '6.0L Twin-Turbo W12',
      horsepower: 626,
      topSpeed: 198,
    },
  },
  {
    _id: '3',
    name: 'Huracán',
    brand: 'Lamborghini',
    model: 'Huracán',
    image: '/cars/lamborghini-huracán.jpg',
    price: 68750000,
    category: 'exotic',
    year: 2024,
    description: 'Raw power and adrenaline-pumping performance in every drive',
    specifications: {
      engine: '5.2L Naturally Aspirated V10',
      horsepower: 631,
      topSpeed: 202,
    },
  },
  {
    _id: '4',
    name: 'Phantom',
    brand: 'Rolls-Royce',
    model: 'Phantom',
    image: '/cars/porsche-911.jpg',
    price: 96250000,
    category: 'luxury',
    year: 2024,
    description: 'The pinnacle of automotive luxury and prestige',
    specifications: {
      engine: '6.75L Twin-Turbo V12',
      horsepower: 563,
      topSpeed: 150,
    },
  },
  {
    _id: '5',
    name: 'F8 Tributo',
    brand: 'Ferrari',
    model: 'F8',
    image: '/cars/lamborghini-huracán.jpg',
    price: 77000000,
    category: 'exotic',
    year: 2024,
    description: 'A tribute to Ferrari\'s greatest front-engine performance cars',
    specifications: {
      engine: '3.9L Twin-Turbo V8',
      horsepower: 710,
      topSpeed: 211,
    },
  },
  {
    _id: '6',
    name: 'AMG GT 63',
    brand: 'Mercedes-AMG',
    model: 'GT 63',
    image: '/cars/bentley-continental.jpg',
    price: 42900000,
    category: 'sports',
    year: 2024,
    description: 'German engineering meets pure performance mastery',
    specifications: {
      engine: '4.0L Bi-Turbo V8',
      horsepower: 630,
      topSpeed: 198,
    },
  },
];
